### ISSUE TITLE
Any suggestions for applying AEVA under white box conditions？

### ISSUE THREAD

**Issue by dongdong4fei** [JunfengGo/AEVA-Blackbox-Backdoor-Detection-main#2]
Hi Junfeng，
First of all, thank you for your excellent work!

I wonder if I want to apply the proposed detection rule under a white box condition, is there any suitable white box adversarial attack method to replace HSJA? 
I hope to get some suggestions for the modification, thanks!

**Comment by JunfengGo** [comment]
Hi, thanks for your interest. I think PGD with l_2 constraints and C&W are OK!

**Comment by JunfengGo** [comment]
> 

If you are interested in our work and inspired from our work, could you cite and star this repository! X_X

**Comment by dongdong4fei** [comment]
> u

Of course！ starred~

According to my understanding, PGD expects that the norm of generated perturbation does not exceed the threshold, rather than taking the smaller norm of perturbation as a part of optimization, which seems inconsistent with the adversarial optimization objective in the paper. Will the difference of perturbation affect the subsequent analysis in the paper?

**Comment by dongdong4fei** [comment]
Of course！ starred~

According to my understanding, PGD expects that the norm of generated perturbation does not exceed the threshold, rather than taking the smaller norm of perturbation as a part of optimization, which seems inconsistent with the adversarial optimization objective in the paper. Will the difference of perturbation affect the subsequent singularity phenomenon analysis in the paper?

**Comment by JunfengGo** [comment]
> 

Sure. It will affect i think. However, if we use extreme value analysis on these perturbation the results would be the same.

**Comment by JunfengGo** [comment]
> Of course！ starred~
> 
> According to my understanding, PGD expects that the norm of generated perturbation does not exceed the threshold, rather than taking the smaller norm of perturbation as a part of optimization, which seems inconsistent with the adversarial optimization objective in the paper. Will the difference of perturbation affect the subsequent singularity phenomenon analysis in the paper?

Moreover, I think how to adapt the adversarial extreme value analysis to the white-box setting for achieving SOTA performance is interesting and promising.
